### PR TITLE
No Storage resources

### PR DESCRIPTION
**Pull request by ghaith**
Disabled the new load from storage behaviour for Jnario as some suite
generation code was relying on the symentic model which is no longer
provided if the resource is loaded from storage.
I added a NO_XTEND todo note to this because I believe a better fix
would be to avoid the NodeModel all together

### CODE REVIEW

**Comment by borisbrodski** [comment]
Cool, thank you!

Just one thing: chould you please avoid formatting code (and especially comments).
You changed just a couple of lines in each module, but the diff contains 152 lines!

Could you remove those formatting changes easily? If no, I will merge it as it is.

**Comment by ghaith** [comment]
I'll send in a new commit with the formatting removed, sorry about that we have automatic formatting rules in our eclipse setups that i forgot to disable for Jnario

**Comment by borisbrodski** [comment]
Great! Thank you!

**Comment by ghaith** [comment]
OK,
I sent in an new commit with the same title, so this pull request should have the new code I believe

**Comment by borisbrodski** [comment]
Yes, it works :) Cool.

**Pull request merged**
